name: flutter_app_boilerplate_context
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  faker: ^2.0.0
  flutter_app_boilerplate_dependency_injection:
    path: ../dependency_injection/
  flutter:
    sdk: flutter
  fzregex: ^2.0.0
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  http: ^0.13.3
  uuid: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0
flutter:
